// Generated by CoffeeScript 1.6.1
(function() {

  $(document).ready(function() {
    var colors, greet, itr;
    greet = 'Hello, ';
    itr = 0;
    colors = ['black', 'red', 'green'];
    $("h1:first").click(function() {
      $("h1:first").css("color", colors[itr++]);
      if (itr > 2) {
        return itr = 0;
      }
    });
    return $("#prompt").keyup(function() {
      return $("h1:first").text(greet + $("#prompt").val());
    });
  });

}).call(this);
